### PR TITLE
refactor(@vtmn/css): keyboard focus a11y dropdown

### LINKED ISSUE #1266: feat: fix a11y for dropdown component
**Is your request related to a problem? Please describe.**

The dropdown is not a11y conform : 
image
[Example of an accessible dropdown](https://www.w3.org/WAI/ARIA/apg/example-index/listbox/listbox-collapsible.html)
/!\ Careful the link leads to a deprecated documentation

**Describe the solution you'd like**

Improve the a11y to make the component accessible

**Additional context**

[Complete audit of the Design System](https://mail.google.com/mail/u/0/?zx=ekjdis7w8vwm#inbox/FMfcgzGqQmMSRhTlqVrvbkmbFXngFqKh?projector=1&messagePartId=0.1)

### PR DESCRIPTION
**Pull request by GaspardMathon**
## Changes description

- On the summary, an arrow down key will lead you directly to the first item element.
- On the summary, a Tab key will lead you to the group item element.
- On the group item, a Tab key leads you to the next interactive element of the page
- You navigate across the items with the arrow keys
- A Tab key on an item focuses the group item

## Context

The previous keyboard behavior wasn't accessible, a focus trap could occur with the Tab key. It has been rework so that a focus trap can't happen. 

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Other information

The expected behavior is that we can navigate in the item list with the arrow keys. Once on the last element, we go back to the first.

- Close #1266

### CODE REVIEW

**Review by lauthieb — CHANGES_REQUESTED** [review]
Thanks @GaspardMathon for these improvements.

I still see two problems on the demo of dropdown component:

1. I can't quit the dropdown when the menu is open. If I focus without opening the menu, that's ok, I can navigate with `Tab` & `Shift+Tab`. But, when it's open, I can only use arrow keys to move between menu items but impossible for me to quit the dropdown:

CleanShot 2022-10-27 at 23 15 46

2. When we click on an menu item, a checkbox appears that means the menu item is selected. I cannot reproduce this with keyboard by clicking on `Enter` or `Space` bar. It doesn't select the related menu item:

CleanShot 2022-10-27 at 23 19 15

Thanks a lot 🙏

**Comment by lauthieb** [comment]
@GaspardMathon I convert your PR as a draft again as there are still issues.
Thanks!

**Review by lauthieb — CHANGES_REQUESTED** [review]
Thanks @GaspardMathon.
I still have the first problem with focus: 
CleanShot 2022-11-04 at 00 00 55
Just sent you a Slack message in the channel that we have with @thibault-mahe.
Thanks!

**Review by lauthieb — COMMENTED** [review]
As discussed together. It's ok but please delete the last error showed by the storybook a11y plugin.

**Comment by GaspardMathon** [comment]
@lauthieb fixes made. Can you check again and resolve your requested changes please ?

**Review by lauthieb — APPROVED** [review]
That's ok for me, thanks @GaspardMathon 🎉

**Comment by lauthieb** [comment]
@thibault-mahe is it ok for you please? :)

**Review by thibault-mahe — APPROVED** [review]

**Pull request merged**
