### PR TITLE
feat(@vtmn/react): add `VtmnChip` component

### PR DESCRIPTION
**Pull request by 0x2A-git**
## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Check PR name, it must follow the https://www.conventionalcommits.org pattern
- [x] If it's a new component in CSS, ask for design review

## Description

This P.R aims to add Chip to react components ( related issue : #735  )

## Does this introduce a breaking change?

- No

## Other information

❤️ Thank you!

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks @0x2A-git for this contribution! I'll review it next week :)

**Comment by lauthieb** [comment]
Hi @0x2A-git thanks a lot for your answer. Is it possible to meet you in videoconference / call soon in order to speak about your 2 Pull Requests and pair programming together?
You can contact me in our slack: https://join.slack.com/t/decathlon-design/shared_invite/zt-ou0n9qas-n_oamDSVUIqvLqNO1LETJg 
Thanks a lot!
Laurent

**Comment by lauthieb** [comment]
Hello @0x2A-git, as seen together, we will meet each other in one week. For the moment, I convert this PR to draft :)

**Review by GaspardMathon — APPROVED** [review]

**Review by lauthieb — APPROVED** [review]

**Review by lauthieb — CHANGES_REQUESTED** [review]
@0x2A-git thanks for your contribution.
Unfortunately, the `VtmnChip` doesn't work as expected.
1/ There's some intelligence, for example when the variant is `input`, you don't just need to add the CSS class but also add the HTML part that display a button, then we need to check when the user click on the cross etc.
2/ Also, when we add icons, it doesn't work.
3/ You will need to add the same logic with badges.

If you want, we will take the next steps of your contribution. Are you ok with this proposition?

Thanks a lot again.?

**Comment by 0x2A-git** [comment]
> @0x2A-git thanks for your contribution. Unfortunately, the `VtmnChip` doesn't work as expected. 1/ There's some intelligence, for example when the variant is `input`, you don't just need to add the CSS class but also add the HTML part that display a button, then we need to check when the user click on the cross etc. 2/ Also, when we add icons, it doesn't work. 3/ You will need to add the same logic with badges.
> 
> If you want, we will take the next steps of your contribution. Are you ok with this proposition?
> 
> Thanks a lot again.

Hi @lauthieb,

Thanks for pointing out these issues, there's no problem for me if you want to take the next steps on this component, though I've just made 2ffba2b677e175a4ab8813fc7982b344b248711b in order to address the different issues you mentioned.

Also: while I was working on it I came across the badge part, so I added a prop called badgeValue which is a number passed in a VtmnBadge automatically generated by Chip but I'm asking to myself wouldn't it be better to pass a some sort of a JSX Element that represents the VtmnBadge so it would allow full customization of the badge ? Like so : 
```jsx
<VtmnChip badge={<VtmnBadge variant='accent' value='10'  />} />
```

**Review by lauthieb — APPROVED** [review]
Thanks a lot for this great work @0x2A-git 💌

**Pull request merged**
