### PR TITLE
feat(@vtmn/react): add `onClear` prop on `VtmnSearch` component

### PR DESCRIPTION
**Pull request by loutsoi852**
## Changes description
Allow user to call a function when clicking on clear icon

## Context
related to https://github.com/Decathlon/vitamin-web/issues/1197

## Checklist

 
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?
- No

## Other information
Had some issues building the project so I couldn't fully test. But the changes are simple enough
image

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks @loutsoi852 
Can you please sign the CLA as requested?
https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1198
Thanks a lot :)

**Review by lauthieb — APPROVED** [review]

**Comment by loutsoi852** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by loutsoi852** [comment]
Not sure that worked lol, let me figure out how to sign the CLA...

**Comment by loutsoi852** [comment]
Done. For some reason the license page took a very long time to load.

**Pull request merged**
