### PR TITLE
refactor(@vtmn/react): use more conventional types

### PR DESCRIPTION
**Pull request by FredericEspiau**
## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [x] Make sure you are making a pull request against the **main branch** (left side).
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Description

As I've struggled myself with `React` types in `TypeScript` recently and as I've stumbled upon your repo (looking for inspiration for my own `rollup` configuration 😄), I decided to suggest a few changes based on my own experience

I've used this guideline as a reference: https://react-typescript-cheatsheet.netlify.app/

The sections I've used are these ones:
- https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components
- https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase#wrappingmirroring-a-html-element

Following these guidelines may save you a few headaches in the long run 😄  (trust me, I've been there)

Also, I realized the `types` declaration in the `package.json` didn't point to the correct folder where the types are so I've changed this as well

## Does this introduce a breaking change?

- No

## Other information

Nope

❤️ Thank you!

Awww you're welcome ❤️

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks a lot @FredericEspiau for your contribution!! For me it's ok.
@amen-souissi @hyacintheknobloch @Ben-Wintrebert & other TypeScript/React developers @Decathlon/front-end what's your opinion please?

**Review by lauthieb — APPROVED** [review]

**Review by amen-souissi — APPROVED** [review]
Makes sense to me.

**Comment by FredericEspiau** [comment]
No opinion about this @jleveugle ? 😄

**Review by jleveugle — APPROVED** [review]

**Comment by jleveugle** [comment]
👍 @FredericEspiau, I'm glad to see a contribution from you once again !

**Comment by lauthieb** [comment]
Let's merge!
Thanks again @FredericEspiau 🙏

**Pull request merged**
