### PR TITLE
feat(@vtmn/react): keep the last focused VtmnTabsItem in a focus state

### PR DESCRIPTION
**Pull request by MaelthiS**
Original issue : https://github.com/Decathlon/vitamin-web/issues/1265

* When we focus on a VtmnTabsItem, and then focus outside the component, we lose the attribute aria-selected=true on the last focused VtmnTabsItem. This makes strange behavior because at least one of the VtmnTabsItem should always have the focus state.

Example here https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-manual.html. You can see that one tab always have a focused state, or a visual indication that it was the last consulted.

## Context
This change is required because this should be the default behavior of a Tab system, one of the tab should always have an indication that it is active. Tabs always have one tab opened, or active. 

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

### CODE REVIEW

**Review by lauthieb — COMMENTED** [review]
Hi @MaelthiS,

Thanks for your proposition.

I agree with what you said. But I have a problem regarding the responsibility of the `VtmnTabsItem`, I think this check needs to be done on `VtmnTabs` which is responsible to manage all items and not did inside each item (because it's only concerned is the last). Do you think it could be possible to propose a change at `VtmnTabs` level and spread down to the `VtmnTabsItems` concerned this update?

Also, can you please ensure that we will not have breaking changes for people that already consumes our `@vtmn/react` library?

Thank you very much for your help on this community library.

**Comment by MaelthiS** [comment]
@lauthieb as today, the VtmnTabs calls just children, so we can't pass props in an easy way. This would need a rewrite of both components, and would add some breaking changes.
I can propose you to do this evolution in a second time, but as for now, we really need this fix. This could be the first step, and then we would do the evolution. What do you think ?

**Comment by thibault-mahe** [comment]
Hi @MaelthiS, thanks for your work!
If I understand well, the onBlur doesn't seems to work that much, and your are suggesting to remove all aria-selected of the sibling on each focus, to only set the aria-selected on the active one.

I'll join Laurent on this one, do you think there would be a way to manage the state of the component higher up on the parent (like a compound component for example) and possibly also to get out of this imperative approach?

Thanks! :)

**Comment by thibault-mahe** [comment]
Hello again @MaelthiS,

after discussion with @lauthieb, and because of your emergency, we will validate this PR as-is so that you can move forward. And then do as you said, i.e. rework with you the component to make it cleaner.

Before any merge, and this is a question that is systematically asked in the PR, can you make sure that these modifications will not bring any breaking changes for those who already use the component please?

Thank you!

**Review by lauthieb — APPROVED** [review]

**Comment by thibault-mahe** [comment]
Hello @MaelthiS, is this PR still relevant? Have you been able to determine if it brought any breaking changes?
Thanks :)

**Comment by lauthieb** [comment]
Hello @MaelthiS, thanks for this!
So for me it's ok. I let @thibault-mahe merge :)

**Comment by thibault-mahe** [comment]
Done, thanks again @MaelthiS :)

**Pull request merged**
