### PR TITLE
fix(@vtmn/svelte): `VtmnSelect` autocomplete

### PR DESCRIPTION
**Pull request by lauthieb**
## Changes description

Related comment on our Slack. Thanks a lot Jordi & Kevin:

CleanShot 2022-08-20 at 00 46 19

## Context

`autocomplete` valid values are `"on"` & `"off"`.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

### CODE REVIEW

**Comment by Tlahey** [comment]
@lauthieb thanks for the fix ! 

What do you think about to keep the same semantic input ? 

To change autocomplete for an enum on / off ?

We have to check if this component are already used on projets.

**Comment by lauthieb** [comment]
@Tlahey or maybe delete this useless prop because already supported by HTML?

**Comment by Tlahey** [comment]
Yes of course !

**Comment by lauthieb** [comment]
> Yes of course !

@Tlahey done ✅

**Review by thibault-mahe — COMMENTED** [review]
Everything looks good to me, thank you! Note that the autocomplete attribute is indeed not binary / boolean and can have values ​​other than "on" and "off", in particular "current-password", "new-password", etc. :)

**Review by Tlahey — APPROVED** [review]

**Pull request merged**
