### PR TITLE
feat: new icons

### PR DESCRIPTION
**Pull request by lauthieb**
## Changes description

Close #1307 

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

### CODE REVIEW

**Comment by lauthieb** [comment]
Hi! @thibault-mahe I let you check this 🙏

**Review by thibault-mahe — CHANGES_REQUESTED** [review]
7 icons (`logout-line`, `run-fill`, `run-line`, `sparkles-fill`, `sparkles-line`, `tablet-fill`, `tablet-line`) are using `clip-path` combined with `url()`, meaning they cannot be used consistently with the `<use>` SVG strategy.

See https://github.com/Decathlon/vitamin-web/issues/1313 and https://github.com/Decathlon/vitamin-design/issues/135 

Can these icons be reworked without the use of `url()` function please ?

**Comment by thibault-mahe** [comment]
The problem has been identified and a global solution (including existing icons) should be proposed in a future PR. I merge as is. Thank you!

**Review by thibault-mahe — APPROVED** [review]

**Comment by lauthieb** [comment]
Thanks @thibault-mahe, as discussed, this is another problem as we already have this problem for a lot of icons already in `main` branch. I think we can merge this and follow the problem with #1315 for icons & assets

**Pull request merged**
