### PR TITLE
feat: add CSS styles for text input

### PR DESCRIPTION
**Pull request by gabbloquet**
## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [x] Make sure you are making a pull request against the **main branch** (left side).
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Description

Please describe your Pull Request.

## Does this introduce a breaking change?

- No

## Other information

❤️ Thank you!

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks, @gabbloquet for this draft PR, nice job!
I've just renamed your PR by removing the "component" part since we haven't decided our architecture for components yet. See #25.
Thanks for your understanding!

**Comment by 0blmail** [comment]
👀

**Comment by lauthieb** [comment]
@gabbloquet after several updates & one mistake I've lost your commit in this branch sorry.
Can you please push again your branch?

**Comment by gabbloquet** [comment]
@lauthieb DONE :) #68 :D

**Pull request closed without merging**
