### PR TITLE
feat(`@vtmn/css`, `@vtmn/svelte`, `@vtmn/react`, `@vtmn/vue`): `VtmnChip` variant `input` match now the figma specs

### PR DESCRIPTION
**Pull request by Tlahey**
## Changes description

https://github.com/Decathlon/vitamin-web/issues/1455

Expected behaviour
image
Source : https://www.decathlon.design/726f8c765/p/08dbe1-chip/b/50988a

## Context
Today, the chip have to be "selected" in order to display the cancel button 
image

This PR aim to disable the selected on the variant input and by default, displayed the cancel button

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Does this introduce a breaking change?

- No

### CODE REVIEW

**Review by lauthieb — APPROVED** [review]

**Comment by lauthieb** [comment]
Hi @Tlahey, thanks for this contribution!
Can you please confirm that this PR will not cause any breaking change and that we can bump packages with a minor release for each of them?
Thanks 🙏

**Comment by Tlahey** [comment]
Hello @lauthieb 
This enhancement will change the behaviour of the VpChip (caus' the select on the input disappears)

We can put a breaking change on the design but the input properties doesn't changed on the component.
The changes are only scoped on the "input" variant

**Comment by lauthieb** [comment]
Thanks @Tlahey for this explanation.
What do you mean about applying a BREAKING CHANGE for design?
You mean bump to major release your changes? Or just in Figma with a communication?
Thank you

**Comment by Tlahey** [comment]
Hello @lauthieb 
Because the design now match the figma's version, the user who used the `VtmnChip` with a input variant will have changes when it will upgrade the version.

**Comment by lauthieb** [comment]
Hi @Tlahey,
Ok, thank you. So, I will merge it with a "BREAKING CHANGE" :)

**Pull request merged**
