### PR TITLE
feat(@vtmn/vue): display icon with `VtmnIcon`  and remove useless type in `VtmnButton`

### PR DESCRIPTION
**Pull request by ThomasLaigneauDecathlon**
## Changes description

Use `VtmnIcon` to display icon inside `VtmnButton`and remove useless type

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.

## Does this introduce a breaking change?

- No

### CODE REVIEW

**Review by lauthieb — CHANGES_REQUESTED** [review]
Thanks @ThomasLaigneauDecathlon but there is a problem with colors and spacings.

# before your PR

CleanShot 2022-03-01 at 09 16 10

# After your PR 

CleanShot 2022-03-01 at 09 15 38

**Comment by ThomasLaigneauDecathlon** [comment]
Fixed it ! I needed to inherit color and font-size VtmnIcon form the VtmnButton.

Added default style like in the React component. Icons should be display properly now.

**Comment by lauthieb** [comment]
Hi @ThomasLaigneauDecathlon thanks! There's still a big space on the left icon: 
CleanShot 2022-03-01 at 22 21 05@2x

**Comment by lauthieb** [comment]
@ThomasLaigneauDecathlon there's another problem (not related to this PR but for the `VtmnButton` component in Vue)

This code doesn't work:

```vue
<slot :v-if="!iconAlone" />
```

To reproduce, you can try to set a value for the iconAlone prop on Storybook. We still see the slot "Button".

**Review by lauthieb — APPROVED** [review]
Perfect! Thanks a lot @ThomasLaigneauDecathlon :tada:

**Pull request merged**
