### PR TITLE
feat(`@vtmn/react`, `@vtmn/vue`, `@vtmn/svelte`): add summaryComponent on `VtmnAccordion`

### LINKED ISSUE #1438: feat(`@vtmn/svelte`, `@vtmn/vue`, `@vtmn/react`): add summary as slot for `VtmnAccordion`
In order to add a badge on the summary, we have to add the summary as a slot.

image

To avoid breaking changes, we have to keep the property summary and if the slot exist, this one is has priority over the summary property.

### PR DESCRIPTION
**Pull request by Tlahey**
## Changes description
Add a new slot `summaryComponent` in order to put more informations than only a string.
No breaking changes here, only override the `summary` property if `summaryComponent` is found.

## Context
Closes #1438
For a new filter component on NFS, we want to create a accordion with a badge information.

image

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Does this introduce a breaking change?

- No

## Other information

image

### CODE REVIEW

**Comment by lauthieb** [comment]
Thanks @Tlahey.
@Sabrinavigil @SimonLeclercq @MARIEDELATTRE do you think that's possible to do this on the summary of the Accordion component (Web)? 
Thanks in advance for your help.

**Review by thibault-mahe — APPROVED** [review]

**Comment by MARIEDELATTRE** [comment]
Hi, from a design point of view the number of filters selected doesn't bring any value to the UX. It's better to show what is selected with chips for example (outside the accordion) like on the website.
CleanShot 2023-06-15 at 11 58 54@2x
My reco is to validate with your designer if you implement chips I think it could be ok to don't have the badge in tehe accordion (which bring zero value).

**Comment by Tlahey** [comment]
Hello @MARIEDELATTRE , the feature come from a mock from UX designer Alexandre Nacache and we have done a meet with @Sabrinavigil. 

You can check the figma here -> https://www.figma.com/file/hn0KOvc9OrEsMe7ruPRrKO/%5BPLP%5D-Revamp-Filters-%E2%9A%99%EF%B8%8F?type=design&node-id=5309-188572&t=KfNBqcOKi5IpvjgS-0

**Comment by lauthieb** [comment]
Hi @Tlahey, after discussing with @Sabrinavigil, we will accept your request.
It will cause a dephasing between the design & dev of Vitamin, but we don't want to hold you back and we've validated this behavior.
Thank you.

**Review by lauthieb — APPROVED** [review]

**Pull request merged**
